#!/usr/bin/env bash

set -euox pipefail

if [ "$#" -ne 2 ]; then
  >&2 echo "$0: Script requires two arguments, token and package ID"
  exit 1
fi

unset token
unset id
token=$1
id=$2

curl -X POST \
  -H "Accept: application/vnd.github.package-deletes-preview+json" \
  -H "Authorization: bearer ${token}" \
  -d '{"query" : "mutation { deletePackageVersion(input : { packageVersionId : \"'"${id}"'\" }) { success } }"}' \
  https://api.github.com/graphql
