name: pre-merge-ci

on: push

jobs:
  create-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: actions-docker-test
      - name: 'Make docker image'
        run: |
          docker build -t my-docker-image actions-docker-test
      - name: 'List images'
        run: |
          docker image ls -a
      - name: 'Save image'
        run: |
          docker save my-docker-image | 7z a -si -bd -tgzip my-docker-image.tar.gz
      - name: 'Create image artifact'
        uses: actions/upload-artifact@v1
        with:
          name: my-docker-image
          path: my-docker-image.tar.gz
  run:
    runs-on: ubuntu-latest
    needs: create-image
    steps:
      - name: 'Pull image artifact'
        uses: actions/download-artifact@v1
        with:
          name: my-docker-image
      - name: 'Load image'
        run: |
          7z e -so -bd -tgzip my-docker-image/my-docker-image.tar.gz | docker load
      - name: 'List images'
        run: |
          docker image ls -a
      - name: 'Run'
        run: |
          docker run --rm my-docker-image
