name: pre-merge-ci

on: push

jobs:
  create-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: actions-docker-test
      - name: 'Authenticate to docker registry'
        run: |
          docker login -u nategraff-sifive -p ${{ secrets.SECRET_TOKEN }} docker.pkg.github.com
      - name: 'Make docker image'
        run: |
          docker build -t my-docker-image actions-docker-test
      - name: 'List images'
        run: |
          docker image ls -a
      - name: 'Push image to registry'
        run: |
          docker tag my-docker-image docker.pkg.github.com/nategraff-sifive/actions-docker-test/my-docker-image:latest
          docker push docker.pkg.github.com/nategraff-sifive/actions-docker-test/my-docker-image:latest
  run:
    runs-on: ubuntu-latest
    needs: create-image
    steps:
      - name: 'Authenticate to docker registry'
        run: |
          docker login -u nategraff-sifive -p ${{ secrets.SECRET_TOKEN }} docker.pkg.github.com
      - name: 'Pull image artifact'
        run: |
          docker pull docker.pkg.github.com/nategraff-sifive/actions-docker-test/my-docker-image:latest
          docker tag docker.pkg.github.com/nategraff-sifive/actions-docker-test/my-docker-image:latest my-docker-image
      - name: 'List images'
        run: |
          docker image ls -a
      - name: 'Run'
        run: |
          docker run --rm my-docker-image
  cleanup:
    runs-on: ubuntu-latest
    needs: run
    steps:
      - uses: actions/checkout@v2
        with:
          path: actions-docker-test
      - name: "Get list of packages"
        run: |
          ${GITHUB_WORKSPACE}/actions-docker-test/github-find-packages ${{ secrets.SECRET_TOKEN }} ${{ github.repository }} > packages.json
      - name: "Print list of packages"
        run: |
          cat packages.json
      - name: "Delete packages"
        run: |
          jq -r .data.repository.packages.nodes[].latestVersion.id packages.json | xargs -n 1 ${GITHUB_WORKSPACE}/actions-docker-test/github-delete-package ${{ secrets.SECRET_TOKEN }}
