name: pre-merge-ci

on: push

jobs:
  create-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: actions-docker-test
      - name: 'Make docker image'
        run: |
          docker build -t my-docker-image actions-docker-test
      - name: 'List images'
        run: |
          docker image ls -a
  run:
    needs: create-image
    container:
      image: my-docker-image
    steps:
      - run: |
          echo "Hello, world"
